# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='tag',
            name='proxy',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa')], max_length=20, null=True, verbose_name='\u4ee3\u7406'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
