# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('users', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_create_user', to='users.Userprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_tag', to='tags.Tag', verbose_name='\u5e73\u53f0'),
        ),
        migrations.AddField(
            model_name='review',
            name='updateuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank_update_user', to='users.Userprofile'),
        ),
    ]
