# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20180813_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='total',
        ),
        migrations.AlterField(
            model_name='review',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='review',
            name='createuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_create_user', to='users.Userprofile', verbose_name='\u521b\u5efa\u4eba'),
        ),
        migrations.AlterField(
            model_name='review',
            name='end',
            field=models.IntegerField(default=10, verbose_name='\u8bc4\u8bba\u95f4\u9694\u81f3'),
        ),
        migrations.AlterField(
            model_name='review',
            name='keyword',
            field=models.CharField(max_length=250, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='review',
            name='start',
            field=models.IntegerField(default=5, verbose_name='\u8bc4\u8bba\u95f4\u9694\u4ece'),
        ),
        migrations.AlterField(
            model_name='review',
            name='starttime',
            field=models.DateTimeField(null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updateuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank_update_user', to='users.Userprofile', verbose_name='\u66f4\u65b0\u4eba'),
        ),
    ]
