# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20180814_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='end',
        ),
        migrations.RemoveField(
            model_name='review',
            name='start',
        ),
    ]
