# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20180814_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '\u4efb\u52a1', 'verbose_name_plural': '\u4efb\u52a1'},
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
