# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20180814_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='option',
            field=models.IntegerField(choices=[(0, '\u81ea\u5bfc\u4e70\u624b\u53f7'), (1, '\u7cfb\u7edf\u4e70\u624b\u53f7')], default='0', verbose_name='\u8d26\u53f7\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sync_flag',
            field=models.IntegerField(default=0, verbose_name='\u5df2\u5206\u914d'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sync_review',
            field=models.IntegerField(default=0, verbose_name='\u5df2\u5b8c\u6210'),
        ),
    ]
