# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20180814_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sync_flag',
            field=models.BooleanField(default=0, verbose_name='\u5df2\u5206\u914d'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sync_review',
            field=models.BooleanField(default=0, verbose_name='\u5df2\u5b8c\u6210'),
        ),
    ]
