# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20180814_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='delflag',
        ),
        migrations.RemoveField(
            model_name='task',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='task',
            name='review_flag',
        ),
    ]
