# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20180814_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='sync_review',
            new_name='finish',
        ),
    ]
