# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_auto_20180814_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='keyword',
            new_name='asin',
        ),
    ]
