# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('account', '0002_auto_20180813_1425'),
        ('review', '0012_auto_20180814_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=250, verbose_name='ASIN')),
                ('comment', models.TextField(null=True, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u5206\u914d\u65f6\u95f4')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='\u9884\u7ea6\u65f6\u95f4')),
                ('reviewtime', models.DateTimeField(blank=True, null=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('reviewid', models.CharField(max_length=50, null=True, verbose_name='\u8bc4\u8bbaID')),
                ('status', models.BooleanField(default=0, verbose_name='\u5df2\u8bc4\u8bba')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_account', to='account.Account', verbose_name='\u8bc4\u8bba\u8d26\u53f7')),
                ('createuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_by', to='users.Userprofile', verbose_name='\u521b\u5efa\u4eba')),
            ],
            options={
                'db_table': 'queue',
                'verbose_name': '\u5bf9\u5217',
                'verbose_name_plural': '\u5bf9\u5217',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='starttime',
            field=models.DateTimeField(null=True, verbose_name='\u9884\u7ea6\u65f6\u95f4'),
        ),
    ]
