# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_auto_20180814_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': '\u961f\u5217', 'verbose_name_plural': '\u961f\u5217'},
        ),
        migrations.AlterField(
            model_name='queue',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_account', to='account.Account', verbose_name='\u8bc4\u8bba\u8d26\u53f7'),
        ),
    ]
