# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_auto_20180814_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='comment',
        ),
        migrations.AddField(
            model_name='queue',
            name='content',
            field=models.TextField(default='', verbose_name='\u5185\u5bb9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='title',
            field=models.CharField(default=2, max_length=200, verbose_name='\u6807\u9898'),
            preserve_default=False,
        ),
    ]
