# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_queue_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='name_type',
            field=models.IntegerField(choices=[(0, '\u9ed8\u8ba4\u59d3\u540d'), (1, '\u7537\u540d'), (2, '\u5973\u540d'), (3, '\u533f\u540d')], default='0', verbose_name='\u7559\u8bc4\u59d3\u540d'),
        ),
    ]
