# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_queue_name_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='review.Task', verbose_name='\u4efb\u52a1'),
            preserve_default=False,
        ),
    ]
