# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_queue_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='starttime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u9884\u7ea6\u65f6\u95f4'),
        ),
    ]
