# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_auto_20180815_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='starttime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='\u9884\u7ea6\u65f6\u95f4'),
        ),
    ]
