# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='\u90ae\u7bb1')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='\u5bc6\u7801')),
                ('cookies', models.TextField(null=True, verbose_name='cookie')),
                ('enable_cookie', models.NullBooleanField(default=None, verbose_name='cookie\u662f\u5426\u53ef\u7528')),
                ('enable_review', models.BooleanField(default=1, verbose_name='\u662f\u5426\u5141\u8bb8\u8bc4\u8bba')),
                ('review_flag', models.BooleanField(default=0, verbose_name='\u662f\u5426\u5df2\u8bc4\u8bba')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('delflag', models.IntegerField(default=0, verbose_name='\u5220\u9664\u6807\u5fd7')),
            ],
            options={
                'db_table': 'account',
                'verbose_name': '\u8d26\u53f7',
                'verbose_name_plural': '\u8d26\u53f7',
            },
        ),
    ]
