# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('users', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='createuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_create_user', to='users.Userprofile', verbose_name='\u521b\u5efa\u4eba'),
        ),
        migrations.AddField(
            model_name='account',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_tag', to='tags.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='account',
            name='updateuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_update_user', to='users.Userprofile', verbose_name='\u66f4\u65b0\u4eba'),
        ),
    ]
