# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180813_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='delflag',
        ),
        migrations.AlterField(
            model_name='account',
            name='enable_review',
            field=models.IntegerField(default=0, verbose_name='\u662f\u5426\u5141\u8bb8\u8bc4\u8bba'),
        ),
    ]
