# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180814_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='enable_review',
            field=models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u72b6\u6001'),
        ),
    ]
