# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180827_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='others',
            name='status',
            field=models.CharField(blank=True, choices=[('Y', '\u5df2\u6ce8\u518c'), ('N', '\u672a\u6ce8\u518c')], default='N', max_length=20, null=True, verbose_name='\u6ce8\u518c\u72b6\u6001'),
        ),
    ]
