# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180827_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='others',
            name='updatetime',
        ),
        migrations.RemoveField(
            model_name='others',
            name='updateuser',
        ),
    ]
