# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180827_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='others',
            options={'verbose_name': '\u8d26\u53f7', 'verbose_name_plural': '\u8d26\u53f7'},
        ),
    ]
