# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seckill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=100, verbose_name=b'ASIN')),
                ('kill_percent', models.IntegerField(default=0, verbose_name=b'\xe7\xa7\x92\xe6\x9d\x80\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('now_percent', models.IntegerField(default=0, verbose_name=b'\xe5\xbd\x93\xe5\x89\x8d\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('begin_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('hours', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe5\x89\xa9\xe4\xbd\x99\xe6\x97\xb6\xe9\x97\xb4')),
                ('count', models.IntegerField(default=0, verbose_name=b'\xe5\xb7\xb2\xe5\x8a\xa0\xe8\xb4\xad\xe6\xac\xa1\xe6\x95\xb0')),
                ('status', models.CharField(choices=[(b'begin', b'\xe6\x9c\xaa\xe5\xbc\x80\xe5\xa7\x8b'), (b'process', b'\xe8\xbf\x90\xe8\xa1\x8c\xe4\xb8\xad'), (b'stop', b'\xe5\xb7\xb2\xe5\x81\x9c\xe6\xad\xa2'), (b'end', b'\xe5\xb7\xb2\xe7\xbb\x93\xe6\x9d\x9f')], default=b'begin', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('tag', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='tags.Tag', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe')),
            ],
            options={
                'db_table': 'seckill',
                'verbose_name': '\u79d2\u6740',
                'verbose_name_plural': '\u79d2\u6740',
            },
        ),
    ]
